### ISSUE TITLE
--k parameter not functional?

### ISSUE THREAD

**Issue by petulla** [yumeng5/CatE#3]
Trying to understand what --k does.

Even with --k at 2, I still see training at further depth:

```sh
Category (japan): 	japan japanese tokyo yashiro nippon
Category (china): 	china beijing chinese li ''china
Category (britain): 	britain british wales p.l.c sainsbury
Category (russia): 	russia russian kremlin vladimir moscow
Category (germany): 	germany west_germany german east_germany west_german
Category (canada): 	canada alberta ontario ottawa saskatchewan
Category (france): 	france french paris chirac belgique
```

Should the category depth continue to 10 or be stopping early in training? I only need to go, say, 3 or 4 levels deep.

**Comment by yumeng5** [comment]
Hi,

The `-k` parameter controls the number of terms per category to be saved into the result file. In other words, it does not control the training process, but only influences how the results are stored. To early stop training, you can set a smaller value of `-iter`.

Thanks,
Yu

**Comment by petulla** [comment]
Thanks.
