### ISSUE TITLE
outputs

### ISSUE THREAD

**Issue by argideritzalpea** [yumeng5/CatE#5]
The outputs of the scripts are not apparent from the readme of the repo. What is the set of things that may be returned from running the code?

**Comment by yumeng5** [comment]
Hi,

The CatE algorithm trains word and topic embeddings which will be saved in files specified by command line arguments `-word-emb` and `-topic-emb`, respectively. Also, the topic mining results (lists of terms retrieved for each topic) will be saved in the file specified by `-res`. You can refer to [run.sh](https://github.com/yumeng5/CatE/blob/master/run.sh) for examples.

Best,
Yu
