### ISSUE TITLE
For help

### ISSUE THREAD

**Issue by perveil** [yumeng5/CatE#8]
hi yumeng：
  i am a new researcher in this field，i want to know after this model，how to do a classification task！in the paper，did you use the model of  WeSTClass to classify the type of  document？

BEST

a student from PKU.

**Comment by yumeng5** [comment]
Hi @perveil ,

For document classification, we directly used the learned word embedding by CatE as the input word representation to WeSTClass (i.e., replacing the word2vec embedding in WeSTClass with the CatE embedding learned on the same corpus).

Best,
Yu
