### ISSUE TITLE
Document Embedding

### ISSUE THREAD

**Issue by pritomsaha** [yumeng5/CatE#9]
This method also learns document embedding. I was wondering how to get those document embeddings as output? Thanks!

**Comment by yumeng5** [comment]
Hi @pritomsaha ,

You could uncomment [this line](https://github.com/yumeng5/CatE/blob/d17640eeb0efd1eb881563f23df5bd3f8e8c81af/src/cate.c#L1108) and use the command line argument `-doc` to specify a path to save document embeddings.

Best,
Yu

**Comment by pritomsaha** [comment]
Thank you so much!
